### ISSUE TITLE
binary data

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/spatialwidget#40]
each `to_geojson()` function could have an equivalent `to_binary()`, which creates a 'binary' representation of the data so it can use the `binaryData` prop

https://github.com/uber/deck.gl/blob/master/docs/developer-guide/performance.md#on-using-binary-data

**Comment by SymbolixAU** [comment]
Now with [sfheaders](https://github.com/dcooley/sfheaders/issues/41) converting to data.frames and keeping properties, I only need one function which works on data.frames.

So the logic is

1. If required, convert `sf` to data.frame `sfheaders::df::sf_to_df( sf, ..., keep = T )`
2. process arguments, columns, colours as per normal
3. convert to json by-column (`jsonify::api::to_json( lst, by = "column" )`
4. done.

**Comment by dcooley** [comment]
now doing in #52
