### ISSUE TITLE
Compilation failing on Travis

### ISSUE THREAD

**Issue by Robinlovelace** [SymbolixAU/spatialwidget#49]
This may be one that you can close immediately as the binary versions are built, but thought it may be worth flagging this error message from Travis just now: https://travis-ci.org/github/Robinlovelace/geocompr/builds/664617057#L11305

**Comment by Robinlovelace** [comment]
FYI I have addressed that with this commit: https://github.com/Robinlovelace/geocompr/commit/434f3d1ad2c110991bf4bfca54c1a3d3adcbf4c8

**Comment by Robinlovelace** [comment]
Also seems to affect mapdeck: https://travis-ci.org/github/Robinlovelace/geocompr/builds/664810245#L11257

**Comment by dcooley** [comment]
yes - this is a known, and agreed (with CRAN) breaking change to `geojsonsf`. I have a new version of spatialwidget with CRAN waiting to be accepted. 

Will notify when it's accepted so you can re-run your travis builds

**Comment by Robinlovelace** [comment]
Great, please ping me here and close the issue when updated version is on CRAN.

**Comment by dcooley** [comment]
@Robinlovelace  `spatialwidget` is now [back on cran](https://cran.r-project.org/web/packages/spatialwidget/index.html) (will take a few days for windows binarys to be built.

I've submitted mapdeck so hopefully that won't take too long.
